# "Backend" chỉ định cách CMS kết nối với kho mã nguồn của bạn.
backend:
  name: git-gateway # Sử dụng dịch vụ Git Gateway của Netlify để xác thực
  branch: main # Làm việc trên nhánh 'main'

# "media_folder" chỉ định nơi các file ảnh được tải lên sẽ được lưu trong repo.
# "public_folder" chỉ định đường dẫn công khai đến các file ảnh đó trên website.
media_folder: "images/uploads"
public_folder: "/images/uploads"

# "collections" định nghĩa các loại nội dung bạn có thể quản lý.
collections:
  - name: "blog" # ID của bộ sưu tập
    label: "Blog Posts" # Tên hiển thị trên giao diện CMS
    folder: "posts" # Thư mục trong repo nơi các file bài viết được lưu
    create: true # Cho phép tạo bài viết mới
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Mẫu để tạo tên file (ví dụ: 2024-05-15-my-new-post.md)
    fields: # Các trường nhập liệu sẽ hiển thị trên giao diện CMS
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Cover Image", name: "cover_image", widget: "image" }
      - { label: "Excerpt", name: "excerpt", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
