# "backend" chỉ định cách CMS kết nối với kho mã nguồn của bạn.
backend:
  name: github # Sử dụng GitHub làm backend
  # THAY ĐỔI DÒNG DƯỚI ĐÂY!
  # Thay "your-username/your-repo-name" bằng tên người dùng và tên repo của bạn.
  repo: "your-username/my-personal-blog" 
  branch: main # Làm việc trên nhánh 'main'

# Cấu hình nơi lưu trữ các file media (ảnh, video...)
media_folder: "images/uploads" # Thư mục trong repo nơi các file ảnh được lưu
public_folder: "/images/uploads" # Đường dẫn công khai đến các file ảnh đó trên website

# "collections" định nghĩa các loại nội dung bạn có thể quản lý.
# Ở đây chúng ta chỉ có một loại là "Bài viết Blog".
collections:
  - name: "blog" # ID của bộ sưu tập (không thay đổi)
    label: "Blog Posts" # Tên hiển thị trên giao diện CMS
    folder: "posts" # Thư mục trong repo nơi các file bài viết .md được lưu
    create: true # Cho phép tạo bài viết mới
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Mẫu để tạo tên file (ví dụ: 2024-05-15-my-new-post.md)
    fields: # Các trường nhập liệu sẽ hiển thị trên giao diện CMS
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Cover Image", name: "cover_image", widget: "image" }
      - { label: "Excerpt", name: "excerpt", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
